version: "3.9"
services:
  frontend:
    container_name: attack-workbench-frontend
    build: .
    depends_on:
      - rest-api
      - collection-manager
    ports:
      - "18880:80"

  rest-api:
    container_name: attack-workbench-rest-api
    build: ../attack-workbench-rest-api
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://attack-workbench-database/attack-workspace

  collection-manager:
    container_name: attack-workbench-collection-manager
    build: ../attack-workbench-collection-manager
    depends_on:
      - rest-api
    ports:
      - "3001:3001"
    environment:
      - WORKBENCH_HOST=http://attack-workbench-rest-api

  mongodb:
    container_name: attack-workbench-database
    image: mongo
    ports:
      - "27017:27017"
      
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
    ## note:
    ## You can use whatever username or password. Just need to make sure to match pairs below
    ##   MONGO_INITDB_ROOT_USERNAME     , MONGO_INITDB_ROOT_PASSWORD 
    ##   ME_CONFIG_MONGODB_ADMINUSERNAME, ME_CONFIG_MONGODB_ADMINPASSWORD
    #  #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    #  ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
    #  ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
      - ME_CONFIG_MONGODB_SERVER=attack-workbench-database
    #  - ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:mongoadmin@mongo-docker:27017/ 
    depends_on:
      - mongodb
    links:
      - mongodb
